### ISSUE TITLE
How does this compare to the reproject package?

### ISSUE THREAD

**Issue by cdeil** [bwinkel/cygrid#3]
So far I've been using the https://github.com/astrofrog/reproject package?

How does this package compare in terms of features and speed?
I think the algorithm is different, right?

I'll print the paper now and have a look soon:
http://www.aanda.org/articles/aa/full_html/2016/07/aa28475-16/aa28475-16.html

Feel free to close this issue if you don't want to investigate / discuss this.
But if you do ... as a new user that found your package more of less by chance ... I would have found a link to the paper and a short description how `cygrid` compares to `reproject` useful.

**Comment by DanielLenz** [comment]
Thanks for the feedback! I've linked the paper in the readme (dababd2).
`reproject` is based on [`interpolation.map_coordinates`](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.interpolation.map_coordinates.html) and hence uses a spline-interpolation, so yes, the algorithm is quite different. You can have a look at the paper for a more detailed discussion.
We're presenting some benchmarks in the paper, comparing `cygrid`'s performance to different `scipy` interpolation functions. These interpolation functions are the same ones that are used in the `reproject` package, so that might give you an idea about the performance of the package.

**Comment by bwinkel** [comment]
Also, have a look into the Jupyter Notebook _minimal.ipynb_, where we compare cygrid with scipy.griddata (which is probably similar as `map_coordinates`). If you really just want to reproject data, it's probably fine (though slower), but for gridding (raw) data, it may not be the best solution.
